ktor:
  deployment:
    port: 8080
  application:
    modules:
      - flotti.SerializationKt.configureSerialization
      - flotti.RoutingKt.configureRouting

postgres:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5432/flotti?user=postgres"
