ktor:
  deployment:
    port: 8080
  application:
    modules:
      - flotti.SerializationKt.configureSerialization
      - flotti.RoutingKt.configureRouting

postgres:
  url: "jdbc:postgresql://localhost:5432/flotti"
  user: "postgres"
  password: ""
